name: express_car
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.4
  google_sign_in: ^6.1.5
  pinput: ^4.0.0
  http: ^1.2.1
  image_picker: ^1.0.7
  multi_select_flutter: ^4.1.3
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2

  cloudinary_public: ^0.21.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.jpg"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
